### ISSUE TITLE
Request: Daily forecast

### ISSUE THREAD

**Issue by Pirol62** [Danielhiversen/home_assistant_weather_data#10]
Hi, maybe I simply don't know the syntax.
The use case: I need the daily forecast total of precipitation for tomorrow and the day after.

I do have created sensors for 1,2,3,4.... hours.
But the forcast: 24 simply provides the data in exactly 24 hour.
I would like to have the total af Day1, day2 etc.
Does such an attribute exist in the api?

The Meteorologisk institutt integration provides data below forecast, but this is quite complicated to read out when we talk about "tomorrow" and the day after.

**Comment by Danielhiversen** [comment]
No plan to add any more features to this integration.
