### ISSUE TITLE
HACS Installation issue

### ISSUE THREAD

**Issue by michal-ambroziak** [Danielhiversen/home_assistant_weather_data#20]
Unable to add weather_data to HACS 1.11.3:

Repository structure for 0.2.1 is not compliant

**Comment by Danielhiversen** [comment]
Tried with another version?

**Comment by michal-ambroziak** [comment]
I'm not considering downgrade of HACS. Should work with the latest version.

**Comment by Danielhiversen** [comment]
Could you try another version of this component?
Could you provide some more info about what is not compliant?

**Comment by michal-ambroziak** [comment]
In my HA, I go to HACS > Custom repositories and under "Add custom repository URL" I type https://github.com/Danielhiversen/home_assistant_weather_data, I click Add and get an error message: "Repostitory structure for 0.2.1 is not compliant"

screenshot: [https://monosnap.com/file/XIrkzqRZdKXDZ67O8sceXMM43uLuvj](url)

**Comment by Danielhiversen** [comment]
Still an issue?
