### ISSUE TITLE
Status unknown

### ISSUE THREAD

**Issue by KristofVr** [Danielhiversen/home_assistant_weather_data#9]
Hello Daniel,

First off all thank you for providing us an alternative for the famous and widely used yr platform. 
I just updated to the latest HA version and noticed the YR was not working anymore. I immediately started to Google and find this topic. I implemented it ride-away and HA seems to recognize your custom_component. Sadly i'm hitting the status unknown issue.

This is the config I used:
  - platform: weather_data
    monitored_conditions:
      - temperature
      - symbol

![image](https://user-images.githubusercontent.com/7521092/102694377-e1d2b000-4220-11eb-9aef-62af9f9f5aab.png)
Can you please have a look?

**Comment by Danielhiversen** [comment]
Any errors in the log?
